#
# Build openvdb Windows
#

FIND_PACKAGE ( GLEW REQUIRED )

SET(OPENVDB_PLATFORM_COMMON_FILES
)

SET(OPENVDB_PLATFORM_INCLUDES
	${GLEW_INCLUDE_DIR}
)

SET(OPENVDB_COMPILE_DEFS
	# Common to all configurations
	${OPENVDB_SLN_COMPILE_DEFS};_WIN32;NOMINMAX;HALF_EXPORTS
	
	$<$<CONFIG:debug>:${OPENVDB_SLN_DEBUG_COMPILE_DEFS}>
	$<$<CONFIG:checked>:${OPENVDB_SLN_CHECKED_COMPILE_DEFS}>
	$<$<CONFIG:profile>:${OPENVDB_SLN_PROFILE_COMPILE_DEFS}>
	$<$<CONFIG:release>:${OPENVDB_SLN_RELEASE_COMPILE_DEFS}>
)

SET(OPENVDB_LIB_TYPE STATIC)

if (OPENVDB_BUILD_SHARED)
	SET(OPENVDB_LIB_TYPE SHARED)
ENDIF()
