#
#
#

SET ( VDB_RENDER_SOURCE_FILES cmd/openvdb_render/main.cc )
SET_SOURCE_FILES_PROPERTIES ( ${VDB_RENDER_SOURCE_FILES}
 PROPERTIES
 COMPILE_FLAGS "-DOPENVDB_USE_BLOSC ${OPENVDB_USE_GLFW_FLAG}"
)
ADD_EXECUTABLE ( vdb_render
 ${VDB_RENDER_SOURCE_FILES}
 )

TARGET_LINK_LIBRARIES ( vdb_render
 openvdb_static
 ${BLOSC_blosc_LIBRARY}
 ${Openexr_ILMIMF_LIBRARY}
 ${Ilmbase_ILMTHREAD_LIBRARY}
 ${Ilmbase_IEX_LIBRARY}
 )
